name: Node.js CI & Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies (root)
      run: npm install

    # If you have separate frontend/backend folders:
    - name: Install backend dependencies
      run:  npm install

    - name: Install frontend dependencies
      run: cd expense-tracker-frontend && npm install

    # - name: Run tests (optional)
    #   run: npm test

  deploy:
    needs: build  # deploy only if build passes
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu
            if [ ! -d "expense-tracker-api" ]; then
              git clone https://github.com/fnavid26/postgres-with-neon.git expense-tracker-api
            else
              cd expense-tracker-api
              git pull origin main
            fi

            cd /home/ubuntu/expense-tracker-api/
            npm install
            pm2 restart backend || pm2 start node index.js --name backend

            cd /home/ubuntu/expense-tracker-api/expense-tracker-frontend
            npm install
            pm2 restart frontend || pm2 start npm --name frontend -- run dev

